
package cn.aezo.springboot.webservice.cxf.client.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2018-08-15T20:59:27.581+08:00
 * Generated source version: 3.1.8
 */
public final class UserService_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.cxf.webservice.springboot.aezo.cn/", "UserServiceWeb");

    private UserService_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceWeb.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UserServiceWeb ss = new UserServiceWeb(wsdlURL, SERVICE_NAME);
        UserService port = ss.getUserServiceImplPort();

        {
            System.out.println("Invoking getName...");
            java.lang.String _getName_userId = "";
            java.lang.String _getName__return = port.getName(_getName_userId);
            System.out.println("getName.result=" + _getName__return);


        }
        {
            System.out.println("Invoking getAllUser...");
            java.util.List<cn.aezo.springboot.webservice.cxf.client.cxf.User> _getAllUser__return = port.getAllUser();
            System.out.println("getAllUser.result=" + _getAllUser__return);


        }
        {
            System.out.println("Invoking getUser...");
            java.lang.String _getUser_arg0 = "";
            cn.aezo.springboot.webservice.cxf.client.cxf.User _getUser__return = port.getUser(_getUser_arg0);
            System.out.println("getUser.result=" + _getUser__return);


        }

        System.exit(0);
    }

}
