
package cn.aezo.springboot.webservice.cxf.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "UserServiceWeb", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", wsdlLocation = "http://localhost:8080/services/user?wsdl")
public class UserServiceWeb
        extends Service {

    private final static URL USERSERVICEWEB_WSDL_LOCATION;
    private final static WebServiceException USERSERVICEWEB_EXCEPTION;
    private final static QName USERSERVICEWEB_QNAME = new QName("http://service.cxf.webservice.springboot.aezo.cn/", "UserServiceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICEWEB_WSDL_LOCATION = url;
        USERSERVICEWEB_EXCEPTION = e;
    }

    public UserServiceWeb() {
        super(__getWsdlLocation(), USERSERVICEWEB_QNAME);
    }

    public UserServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICEWEB_QNAME, features);
    }

    public UserServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICEWEB_QNAME);
    }

    public UserServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICEWEB_QNAME, features);
    }

    public UserServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns UserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserService getUserServiceImplPort() {
        return super.getPort(new QName("http://service.cxf.webservice.springboot.aezo.cn/", "UserServiceImplPort"), UserService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UserService
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserService getUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.webservice.springboot.aezo.cn/", "UserServiceImplPort"), UserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICEWEB_EXCEPTION != null) {
            throw USERSERVICEWEB_EXCEPTION;
        }
        return USERSERVICEWEB_WSDL_LOCATION;
    }

}
