
package cn.aezo.springboot.webservice.cxf.client.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetNameResponse")
    public String getName(
        @WebParam(name = "userId", targetNamespace = "")
        String userId);

    /**
     * 
     * @return
     *     returns java.util.List<cn.aezo.springboot.webservice.cxf.client.wsimport.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetAllUserResponse")
    public List<User> getAllUser();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.aezo.springboot.webservice.cxf.client.wsimport.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.cxf.webservice.springboot.aezo.cn/", className = "cn.aezo.springboot.webservice.cxf.client.wsimport.GetUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
