server:
  port: 8081

security:
  oauth2:
    client:
      client-id: q8S3J5lmw2lmk7P1iuyi
      client-secret: bHAA7c0pTi9xLUdFzYOgIIccZZ5N21Os
      userAuthorizationUri: https://www.oschina.net/action/oauth2/authorize
      accessTokenUri: https://www.oschina.net/action/openapi/token
      redirect-uri-template: http://oldinaction.xicp.net/login
##       默认access_token
#      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      use-current-uri: false
    resource:
      userInfoUri: https://www.oschina.net/action/openapi/user
    sso:
      login-path: /login